### ISSUE TITLE
Downloadable Product - Downloadable Information

### ISSUE THREAD

**Issue by neonmaccca** [openstream/No-Flash-Image-Uploader#21]
Hi, this plugin works great for the most part, however, when you try to create a downloadable product and then upload Downloadable Information, the flash upload is still present.

Is there any intention to include support for this?

**Comment by nickweisser** [comment]
We only put this extension here because it was removed from Magento connect and we have no plans for adding new features or fixing issues, sorry. If you however want to look into it yourself, any pull request is welcome.

**Comment by zuiko** [comment]
Does somebody could have a solution concerning this remaining issue ?
