### ISSUE TITLE
Cannot get package trough composer

### ISSUE THREAD

**Issue by cristianuibar** [openstream/No-Flash-Image-Uploader#4]
Your package is not listed in packagist.org so I cannot get it trough composer. Please add it.

Thank you!

**Comment by nickweisser** [comment]
Can you do that please? :-)

**Comment by bluec** [comment]
You can install it using composer without it being listed on packagist, read the composer docs. 

Also, it is already listed on [Firegento](http://packages.firegento.com/#!/openstream) which I would argue is the correct place for it to be rather than packagist.

**Comment by cristianuibar** [comment]
I see. Thank you!
