### ISSUE TITLE
Not Working on Safari

### ISSUE THREAD

**Issue by neel-shuvo** [openstream/No-Flash-Image-Uploader#7]
This Extension works fine in all the latest versions of Internet Explorer, Mozilla Firefox, and Google Chrome. In Apple Safari, Only the Uploading Message shows up, But Uploading doesn't complete!

**Comment by nickweisser** [comment]
Thanks for pointing it out, if you're a developer please fix it, otherwise you might have to wait until another developer needs to have this fixed, too.

**Comment by latenzio** [comment]
works in current Safari Version 9.0.3 (11601.4.4)

**Comment by dannevang** [comment]
Can't reproduce that error. I just completed an upload without any issues on Safari. 

What version did you test it on?

**Comment by egorpe** [comment]
Same thing in Chrome, Firefox and Safari

**Comment by egorpe** [comment]
![The Error](http://i.imgur.com/yXqB98N.jpg)

**Comment by egorpe** [comment]
Fix: uploader.js, line 211 replace with `block.parentNode.removeChild(block);`
